language: rust
cache: cargo

rust:
  - nightly

env:
  matrix:
    - SCRIPT="./check.sh"
    - SCRIPT="./build.sh"
    - SCRIPT="./test.sh"

before_script:
  - rustup target add wasm32-unknown-unknown
  - rustup target add i686-pc-windows-gnu
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/cargo-readme || cargo install --vers "^3" cargo-readme)
  - (test -x $HOME/.cargo/bin/wasm-gc || cargo install --vers "^0.1.6" wasm-gc)
  - cargo install-update -a

script:
  - "$SCRIPT"

matrix:
  include:
    - name: "Windows Builds"
      rust: stable
      before_script:
        - rustup target add i686-pc-windows-gnu
      script:
        - cd ./wee_alloc
        - cargo check --release --no-default-features
        - cargo check --release
        - cargo check --release --no-default-features --target i686-pc-windows-gnu
        - cargo check --release                           --target i686-pc-windows-gnu
    - name: "Stable Wasm Builds"
      rust: stable
      before_script:
        - rustup target add wasm32-unknown-unknown
      script:
        - cargo check -p wee_alloc --target wasm32-unknown-unknown
